# Form implementation generated from reading ui file 'probando.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(668, 345)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.labelPass = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelPass.setGeometry(QtCore.QRect(130, 70, 91, 51))
        self.labelPass.setObjectName("labelPass")
        self.SalirBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.SalirBtn.setGeometry(QtCore.QRect(480, 140, 131, 61))
        self.SalirBtn.setObjectName("SalirBtn")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(120, 140, 131, 51))
        self.label_2.setObjectName("label_2")
        self.lineEditUser = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditUser.setGeometry(QtCore.QRect(270, 90, 113, 21))
        self.lineEditUser.setObjectName("lineEditUser")
        self.lineEditPass = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditPass.setGeometry(QtCore.QRect(270, 160, 113, 21))
        self.lineEditPass.setObjectName("lineEditPass")
        self.LimpiarBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.LimpiarBtn.setGeometry(QtCore.QRect(480, 60, 131, 61))
        self.LimpiarBtn.setObjectName("LimpiarBtn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.label_2.setBuddy(self.label_2)

        self.retranslateUi(MainWindow)
        self.LimpiarBtn.clicked.connect(self.lineEditUser.clear) # type: ignore
        self.LimpiarBtn.clicked.connect(self.lineEditPass.clear) # type: ignore
        self.SalirBtn.clicked.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "VentanaInicio"))
        self.labelPass.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:700; font-style:italic;\">USUARIO</span></p></body></html>"))
        self.SalirBtn.setText(_translate("MainWindow", "SALIR"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:700; font-style:italic;\">CONTRASEÑA</span></p></body></html>"))
        self.LimpiarBtn.setText(_translate("MainWindow", "LIMPIAR"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
