# Form implementation generated from reading ui file 'VentanaLogeo.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(539, 343)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Usuariolabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.Usuariolabel.setGeometry(QtCore.QRect(100, 70, 61, 20))
        self.Usuariolabel.setObjectName("Usuariolabel")
        self.PassLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.PassLabel.setGeometry(QtCore.QRect(70, 140, 101, 20))
        self.PassLabel.setObjectName("PassLabel")
        self.UsuariolineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.UsuariolineEdit.setGeometry(QtCore.QRect(190, 70, 113, 21))
        self.UsuariolineEdit.setObjectName("UsuariolineEdit")
        self.PasslineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.PasslineEdit.setGeometry(QtCore.QRect(190, 140, 113, 21))
        self.PasslineEdit.setObjectName("PasslineEdit")
        self.LoginButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.LoginButton.setGeometry(QtCore.QRect(390, 70, 111, 31))
        self.LoginButton.setStyleSheet("font: 600 12pt \"Segoe UI\";\n"
"background-color: rgb(255, 170, 127);")
        self.LoginButton.setObjectName("LoginButton")
        self.RegistroButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.RegistroButton.setGeometry(QtCore.QRect(390, 130, 101, 31))
        self.RegistroButton.setStyleSheet("font: 600 12pt \"Segoe UI\";\n"
"background-color: rgb(255, 170, 127);")
        self.RegistroButton.setObjectName("RegistroButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 539, 33))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Usuariolabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:700; font-style:italic;\">Usuario:</span></p></body></html>"))
        self.PassLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:700; font-style:italic;\">Contraseña:</span></p></body></html>"))
        self.LoginButton.setText(_translate("MainWindow", "Iniciar Sesión"))
        self.RegistroButton.setText(_translate("MainWindow", "Registrarse"))
