# Form implementation generated from reading ui file 'VentanaRegistro.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QMessageBox  

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(539, 343)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        # Etiquetas y campos de texto
        self.Nombrelabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.Nombrelabel.setGeometry(QtCore.QRect(80, 50, 71, 20))
        self.Nombrelabel.setObjectName("Nombrelabel")
        self.Correoolabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.Correoolabel.setGeometry(QtCore.QRect(80, 100, 61, 20))
        self.Correoolabel.setObjectName("Correoolabel")
        self.PassLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.PassLabel.setGeometry(QtCore.QRect(60, 160, 101, 20))
        self.PassLabel.setObjectName("PassLabel")

        self.NombrelineEdit_2 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.NombrelineEdit_2.setGeometry(QtCore.QRect(190, 50, 113, 21))
        self.NombrelineEdit_2.setObjectName("NombrelineEdit_2")
        self.CorreolineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.CorreolineEdit.setGeometry(QtCore.QRect(190, 100, 113, 21))
        self.CorreolineEdit.setObjectName("CorreolineEdit")
        self.PasslineEdit_2 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.PasslineEdit_2.setGeometry(QtCore.QRect(190, 160, 113, 21))
        self.PasslineEdit_2.setObjectName("PasslineEdit_2")

        # Botón de registro
        self.RegistroBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.RegistroBtn.setGeometry(QtCore.QRect(360, 230, 141, 51))
        self.RegistroBtn.setStyleSheet("font: 600 12pt \"Segoe UI\";\n"
                                       "background-color: rgb(255, 170, 127);")
        self.RegistroBtn.setObjectName("RegistroBtn")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 539, 33))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # Conectar el botón de registro a la función
        self.RegistroBtn.clicked.connect(self.registrar_usuario)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Correoolabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:700; font-style:italic;\">Correo:</span></p></body></html>"))
        self.PassLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:700; font-style:italic;\">Contraseña:</span></p></body></html>"))
        self.RegistroBtn.setText(_translate("MainWindow", "Registrarse"))
        self.Nombrelabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:700; font-style:italic;\">Nombre:</span></p></body></html>"))

    def registrar_usuario(self):
        # Obtener los datos ingresados en los campos
        nombre = self.NombrelineEdit_2.text()
        correo = self.CorreolineEdit.text()
        contraseña = self.PasslineEdit_2.text()

        # Comprobar si los campos no están vacíos
        if nombre and correo and contraseña:
            # Mostrar mensaje de confirmación
            QMessageBox.information(None, "Éxito", "Usuario registrado correctamente")
        else:
            # Si algún campo está vacío, mostrar un mensaje de advertencia
            QMessageBox.warning(None, "Error", "Por favor, complete todos los campos")
