# Form implementation generated from reading ui file 'prueba.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(681, 334)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.botonAceptar = QtWidgets.QPushButton(parent=self.centralwidget)
        self.botonAceptar.setGeometry(QtCore.QRect(420, 220, 221, 71))
        self.botonAceptar.setObjectName("botonAceptar")
        self.labelUsuario = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelUsuario.setGeometry(QtCore.QRect(110, 50, 111, 41))
        self.labelUsuario.setObjectName("labelUsuario")
        self.labelContrasenia = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelContrasenia.setGeometry(QtCore.QRect(90, 120, 181, 51))
        self.labelContrasenia.setObjectName("labelContrasenia")
        self.lEusuario = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lEusuario.setGeometry(QtCore.QRect(270, 60, 201, 31))
        self.lEusuario.setObjectName("lEusuario")
        self.lEpass = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lEpass.setGeometry(QtCore.QRect(270, 130, 201, 31))
        self.lEpass.setObjectName("lEpass")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(520, 90, 111, 41))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButton.clicked.connect(self.lEusuario.clear) # type: ignore
        self.pushButton.clicked.connect(self.lEpass.clear) # type: ignore
        self.botonAceptar.clicked.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "VentanaInicio"))
        self.botonAceptar.setText(_translate("MainWindow", "SALIR"))
        self.labelUsuario.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; font-style:italic;\">USUARIO</span></p></body></html>"))
        self.labelContrasenia.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; font-style:italic;\">CONTRASEÑA</span></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "LIMPIAR"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
