# Form implementation generated from reading ui file 'ventanaLogeo.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ventanaRegistro(object):
    def setupUi(self, ventanaRegistro):
        ventanaRegistro.setObjectName("ventanaRegistro")
        ventanaRegistro.resize(685, 238)
        ventanaRegistro.setStyleSheet("background-color: rgb(255, 255, 255);")
        ventanaRegistro.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(parent=ventanaRegistro)
        self.centralwidget.setObjectName("centralwidget")
        self.botonSalir = QtWidgets.QPushButton(parent=self.centralwidget)
        self.botonSalir.setGeometry(QtCore.QRect(560, 180, 111, 41))
        self.botonSalir.setStyleSheet("")
        self.botonSalir.setObjectName("botonSalir")
        self.usuario = QtWidgets.QLabel(parent=self.centralwidget)
        self.usuario.setGeometry(QtCore.QRect(250, 40, 101, 31))
        self.usuario.setObjectName("usuario")
        self.campoUsuario = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.campoUsuario.setGeometry(QtCore.QRect(390, 40, 171, 31))
        self.campoUsuario.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.campoUsuario.setObjectName("campoUsuario")
        self.usuario_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.usuario_2.setGeometry(QtCore.QRect(250, 100, 141, 31))
        self.usuario_2.setObjectName("usuario_2")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(390, 100, 171, 31))
        self.lineEdit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit.setObjectName("lineEdit")
        self.botonLimpiar = QtWidgets.QPushButton(parent=self.centralwidget)
        self.botonLimpiar.setGeometry(QtCore.QRect(580, 70, 97, 33))
        self.botonLimpiar.setObjectName("botonLimpiar")
        self.botonEntrar = QtWidgets.QPushButton(parent=self.centralwidget)
        self.botonEntrar.setGeometry(QtCore.QRect(420, 180, 121, 41))
        self.botonEntrar.setObjectName("botonEntrar")
        self.line = QtWidgets.QFrame(parent=self.centralwidget)
        self.line.setGeometry(QtCore.QRect(250, 150, 421, 20))
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 40, 191, 161))
        self.label.setStyleSheet("border-image: url(:/cct/Descargas/UEM-FONDO Teams.jpg);")
        self.label.setText("")
        self.label.setObjectName("label")
        ventanaRegistro.setCentralWidget(self.centralwidget)

        self.retranslateUi(ventanaRegistro)
        self.botonSalir.clicked.connect(ventanaRegistro.close) # type: ignore
        self.botonLimpiar.clicked.connect(self.campoUsuario.clear) # type: ignore
        self.botonLimpiar.clicked.connect(self.lineEdit.clear) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ventanaRegistro)

    def retranslateUi(self, ventanaRegistro):
        _translate = QtCore.QCoreApplication.translate
        ventanaRegistro.setWindowTitle(_translate("ventanaRegistro", "Ventana de Registro"))
        ventanaRegistro.setAccessibleName(_translate("ventanaRegistro", "Ventana Registro"))
        self.botonSalir.setText(_translate("ventanaRegistro", "SALIR"))
        self.usuario.setText(_translate("ventanaRegistro", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; font-style:italic;\">USUARIO</span></p></body></html>"))
        self.usuario_2.setText(_translate("ventanaRegistro", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; font-style:italic;\">CONTRASEÑA</span></p></body></html>"))
        self.botonLimpiar.setText(_translate("ventanaRegistro", "LIMPIAR"))
        self.botonEntrar.setText(_translate("ventanaRegistro", "ENTRAR"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ventanaRegistro = QtWidgets.QMainWindow()
    ui = Ui_ventanaRegistro()
    ui.setupUi(ventanaRegistro)
    ventanaRegistro.show()
    sys.exit(app.exec())
