# Form implementation generated from reading ui file 'CitaMedica.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("\n"
"background-color: rgb(0, 0, 0);")
        self.centralwidget.setObjectName("centralwidget")
        self.lineNombre = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineNombre.setGeometry(QtCore.QRect(260, 40, 311, 21))
        self.lineNombre.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.lineNombre.setObjectName("lineNombre")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 40, 51, 21))
        self.label.setStyleSheet("color: rgb(255, 255, 0);\n"
"font: 75 8pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(90, 80, 56, 16))
        self.label_2.setStyleSheet("color: rgb(255, 255, 0);\n"
"font: 75 8pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(90, 120, 56, 16))
        self.label_3.setStyleSheet("color: rgb(255, 255, 0);\n"
"font: 75 8pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(50, 160, 101, 20))
        self.label_4.setStyleSheet("color: rgb(255, 255, 0);\n"
"font: 75 8pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.lineApellido = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineApellido.setGeometry(QtCore.QRect(260, 80, 311, 21))
        self.lineApellido.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.lineApellido.setObjectName("lineApellido")
        self.lineTelefono = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineTelefono.setGeometry(QtCore.QRect(260, 120, 311, 21))
        self.lineTelefono.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.lineTelefono.setObjectName("lineTelefono")
        self.fecha_cita = QtWidgets.QDateEdit(parent=self.centralwidget)
        self.fecha_cita.setGeometry(QtCore.QRect(260, 160, 311, 22))
        self.fecha_cita.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.fecha_cita.setObjectName("fecha_cita")
        self.table_registro = QtWidgets.QTableView(parent=self.centralwidget)
        self.table_registro.setGeometry(QtCore.QRect(70, 250, 631, 192))
        self.table_registro.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.table_registro.setObjectName("table_registro")
        self.btnAgregar = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnAgregar.setGeometry(QtCore.QRect(300, 470, 161, 28))
        self.btnAgregar.setStyleSheet("background-color: rgb(0, 255, 127);")
        self.btnAgregar.setObjectName("btnAgregar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Nombre:"))
        self.label_2.setText(_translate("MainWindow", "Apellido:"))
        self.label_3.setText(_translate("MainWindow", "Teléfono:"))
        self.label_4.setText(_translate("MainWindow", "Fecha de la cita:"))
        self.btnAgregar.setText(_translate("MainWindow", "Agregar Cita"))
