# Form implementation generated from reading ui file 'Practica3.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
#import resources


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(786, 350)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(320, 80, 56, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(310, 170, 101, 31))
        self.label_2.setObjectName("label_2")
        self.textUsuario = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textUsuario.setGeometry(QtCore.QRect(420, 80, 221, 31))
        self.textUsuario.setObjectName("textUsuario")
        self.textPass = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textPass.setGeometry(QtCore.QRect(420, 170, 221, 31))
        self.textPass.setObjectName("textPass")
        self.pushLimpiar = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushLimpiar.setGeometry(QtCore.QRect(670, 120, 93, 28))
        self.pushLimpiar.setObjectName("pushLimpiar")
        self.pushEntrar = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushEntrar.setGeometry(QtCore.QRect(530, 240, 93, 28))
        self.pushEntrar.setObjectName("pushEntrar")
        self.pushSalir = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushSalir.setGeometry(QtCore.QRect(670, 240, 93, 28))
        self.pushSalir.setObjectName("pushSalir")
        self.textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(120, 100, 111, 91))
        self.textEdit.setStyleSheet("\n"
"border-image: url(:/logo/icono.jpg);")
        #"C:\Users\Raul\Documents\GitHub\SincronizarEclipse\eclipse-workspace\Simulacro1DI\src\VentanaPython\src\imagenes\icono.jpg"
        self.textEdit.setObjectName("textEdit")
        self.line = QtWidgets.QFrame(parent=self.centralwidget)
        self.line.setGeometry(QtCore.QRect(310, 220, 471, 20))
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 786, 33))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "USUARIO"))
        self.label_2.setText(_translate("MainWindow", "CONTRASEÑA"))
        self.pushLimpiar.setText(_translate("MainWindow", "LIMPIAR"))
        self.pushEntrar.setText(_translate("MainWindow", "ENTRAR"))
        self.pushSalir.setText(_translate("MainWindow", "SALIR"))
