package application;

import javafx.fxml.FXML;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

public class PruebaFXController {
	@FXML
	private Label lblNombre;
	@FXML
	private TextField tfNombre;

	// Event Listener on Button.onAction
	@FXML
	public void actionEntrar(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void actionSalir(ActionEvent event) {
		// TODO Autogenerated
	}
}
