# Form implementation generated from reading ui file 'Ventanaimagen.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(270, 160, 251, 181))
        #self.label.setStyleSheet("\\home\\javi\\eclipse-workspace\\PruebaIamgenPython\\src\\icono.jpg")
        #self.label.setStyleSheet("border-image: url(:/logo/icono.jpg);")
        #ruta_imagen = "/home/javi/eclipse-workspace/PruebaIamgenPython/src/icono.jpg"
        ruta_imagen ="C:/Users/Raul/Documents/GitHub/SincronizarEclipse/eclipse-workspace/PruebaIamgenPython/src/icono.jpg"

        pixmap = QtGui.QPixmap(ruta_imagen)
        if not pixmap.isNull():
            print("Imagen cargada correctamente.")
            self.label.setPixmap(pixmap)
            self.label.setScaledContents(True)  # Ajustar la imagen al QLabel
        else:
            print("Error: No se puede cargar la imagen.")

        self.label.setText("")
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
